# Generated by Django 2.2.7 on 2020-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=33)),
                ('lastName', models.CharField(max_length=33)),
                ('userName', models.CharField(max_length=23)),
                ('mailId', models.CharField(max_length=53)),
                ('phoneNumber', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
