# Generated by Django 2.2.7 on 2020-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
