# Generated by Django 3.0.5 on 2020-04-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.IntegerField(max_length=10)),
                ('stdName', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CSE', 'cse'), ('ECE', 'ece'), ('IT', 'it'), ('EEE', 'eee')], max_length=50)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
